# permissions for end users to view dnscnamerecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dnscnamerecord-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pihole-operator
    app.kubernetes.io/part-of: pihole-operator
    app.kubernetes.io/managed-by: kustomize
  name: dnscnamerecord-viewer-role
rules:
- apiGroups:
  - pihole.lab.johnrowley.co
  resources:
  - dnscnamerecords
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pihole.lab.johnrowley.co
  resources:
  - dnscnamerecords/status
  verbs:
  - get
