apiVersion: pihole.lab.johnrowley.co/v1alpha1
kind: PiHole
metadata:
  labels:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/instance: pihole-sample
    app.kubernetes.io/part-of: pihole-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: pihole-operator
  name: pihole-sample
spec:
  # TODO(user): Add fields here
