//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ASpec) DeepCopyInto(out *ASpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ASpec.
func (in *ASpec) DeepCopy() *ASpec {
	if in == nil {
		return nil
	}
	out := new(ASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNAMESpec) DeepCopyInto(out *CNAMESpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNAMESpec.
func (in *CNAMESpec) DeepCopy() *CNAMESpec {
	if in == nil {
		return nil
	}
	out := new(CNAMESpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsRecord) DeepCopyInto(out *DnsRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsRecord.
func (in *DnsRecord) DeepCopy() *DnsRecord {
	if in == nil {
		return nil
	}
	out := new(DnsRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DnsRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsRecordList) DeepCopyInto(out *DnsRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DnsRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsRecordList.
func (in *DnsRecordList) DeepCopy() *DnsRecordList {
	if in == nil {
		return nil
	}
	out := new(DnsRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DnsRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsRecordSpec) DeepCopyInto(out *DnsRecordSpec) {
	*out = *in
	if in.A != nil {
		in, out := &in.A, &out.A
		*out = new(ASpec)
		**out = **in
	}
	if in.CNAME != nil {
		in, out := &in.CNAME, &out.CNAME
		*out = new(CNAMESpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsRecordSpec.
func (in *DnsRecordSpec) DeepCopy() *DnsRecordSpec {
	if in == nil {
		return nil
	}
	out := new(DnsRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DnsRecordStatus) DeepCopyInto(out *DnsRecordStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DnsRecordStatus.
func (in *DnsRecordStatus) DeepCopy() *DnsRecordStatus {
	if in == nil {
		return nil
	}
	out := new(DnsRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHole) DeepCopyInto(out *PiHole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHole.
func (in *PiHole) DeepCopy() *PiHole {
	if in == nil {
		return nil
	}
	out := new(PiHole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PiHole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHoleList) DeepCopyInto(out *PiHoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PiHole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHoleList.
func (in *PiHoleList) DeepCopy() *PiHoleList {
	if in == nil {
		return nil
	}
	out := new(PiHoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PiHoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHoleSpec) DeepCopyInto(out *PiHoleSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.DNS.DeepCopyInto(&out.DNS)
	if in.DNSRecordSelector != nil {
		in, out := &in.DNSRecordSelector, &out.DNSRecordSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.DNSRecordNamespaceSelector != nil {
		in, out := &in.DNSRecordNamespaceSelector, &out.DNSRecordNamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHoleSpec.
func (in *PiHoleSpec) DeepCopy() *PiHoleSpec {
	if in == nil {
		return nil
	}
	out := new(PiHoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHoleSpecDNS) DeepCopyInto(out *PiHoleSpecDNS) {
	*out = *in
	if in.UpstreamServers != nil {
		in, out := &in.UpstreamServers, &out.UpstreamServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHoleSpecDNS.
func (in *PiHoleSpecDNS) DeepCopy() *PiHoleSpecDNS {
	if in == nil {
		return nil
	}
	out := new(PiHoleSpecDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHoleStatus) DeepCopyInto(out *PiHoleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHoleStatus.
func (in *PiHoleStatus) DeepCopy() *PiHoleStatus {
	if in == nil {
		return nil
	}
	out := new(PiHoleStatus)
	in.DeepCopyInto(out)
	return out
}
