on:
    push:
      branches:
        - main
    # schedule:
    #   - cron: '0 1 * * 1-5' # 1 AM UTC is 5 PM PST/ 6 PM PDT
  
permissions:
  contents: write
  pull-requests: write

name: release
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }} # e.g. v1.0.0
      version: ${{ steps.release-please.outputs.version }} # e.g. 1.0.0
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          release-type: simple
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
  release:
    runs-on: ubuntu-latest
    needs: [release-please]
    if: needs.release-please.outputs.release_created
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v2
      - name: docker-buildx
        run: make docker-buildx VERSION=${{ needs.release-please.outputs.version }}
      - name: bundle
        run: make bundle bundle-build bundle-push VERSION=${{ needs.release-please.outputs.version }}